name: quizzy
description: A Flutter project for propositional logic quiz.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  riverpod: ^2.4.6
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  go_router: ^12.1.1
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.0  
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/po/
    - assets/images/ls/
